using System.Text.Json;

namespace A2A;

/// <summary>
/// Provides the agent with pre-resolved context for the current request.
/// IDs are pre-generated, existing task is pre-fetched from store.
/// </summary>
public sealed class RequestContext
{
    /// <summary>
    /// Default owner scope used when no tenant/owner identity is available (unauthenticated requests).
    /// All unauthenticated callers share this scope, preserving backward compatibility.
    /// </summary>
    public const string DefaultOwner = "";

    /// <summary>The incoming client message.</summary>
    public required Message Message { get; init; }

    /// <summary>Existing task if continuing, null for new conversations.</summary>
    public AgentTask? Task { get; init; }

    /// <summary>The task ID — existing or newly generated.</summary>
    public required string TaskId { get; init; }

    /// <summary>The context ID — client-provided, inherited from existing task, or SDK-generated.</summary>
    public required string ContextId { get; init; }

    /// <summary>
    /// Owner/tenant scope for the current request. Defaults to <see cref="DefaultOwner"/>
    /// for unauthenticated requests. The SDK scopes all task store CRUD by this value,
    /// so tasks created under one owner are not visible to another owner.
    /// </summary>
    public string Owner { get; init; } = DefaultOwner;

    /// <summary>
    /// Whether <see cref="ContextId"/> was provided by the client (or inherited from an existing task)
    /// vs generated by the SDK. Agents backed by inference APIs can use this to decide whether
    /// to reuse an existing conversation or start a new one.
    /// </summary>
    public bool ClientProvidedContextId { get; init; }

    /// <summary>Whether the response will be streamed (SSE) vs returned synchronously.</summary>
    public required bool StreamingResponse { get; init; }

    /// <summary>Client-provided configuration for the send message request, if any.</summary>
    public SendMessageConfiguration? Configuration { get; init; }

    /// <summary>Original request metadata.</summary>
    public Dictionary<string, JsonElement>? Metadata { get; init; }

    /// <summary>First text content from message parts, or null.</summary>
    public string? UserText => Message.Parts.FirstOrDefault(p => p.Text is not null)?.Text;

    /// <summary>Whether this continues an existing task.</summary>
    public bool IsContinuation => Task is not null;
}
