name: Prefix Dependabot PR Titles

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  prefix-title:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix PR title if needed
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const prefix = "chore: ";
            const title = context.payload.pull_request.title;
            if (!title.startsWith(prefix)) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                title: prefix + title
              });
            }
